services:
  emulator:
    platform: linux/amd64
    build:
      context: ./docker/emulator
    image: qemu-emulator
    privileged: true
    environment:
      - ANDROID_EMULATOR_WAIT_TIME=120
      - ANDROID_EMULATED_DEVICE=11
      - ANDROID_EXTRA_OPTS=-gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -no-snapshot-save
      - DEVICE_PORT=5554
      - ENABLE_VNC=true
      - VNC_PORT=5900
    volumes:
      - ./avd-data:/root/.android/avd
    ports:
      - "5901:5900"  # VNC access
      - "5554:5554"  # Emulator console
      - "5555:5555"  # ADB device port
      - "5037:5037"  # ADB server port
    # command: ["/usr/local/bin/start-emulator.sh"]
    command: ["sleep", "infinity"]  # Debug mode - commented out
  emulator14:
    platform: linux/amd64
    build:
      context: ./docker/emulator-android14
    image: qemu-emulator-android14
    privileged: true
    environment:
      - ANDROID_EMULATOR_WAIT_TIME=120
      - ANDROID_EMULATED_DEVICE=14
      - ANDROID_EXTRA_OPTS=-gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -no-snapshot-save
      - DEVICE_PORT=6654
      - ENABLE_VNC=true
      - VNC_PORT=5901
    volumes:
      - ./avd-data:/root/.android/avd
    ports:
      - "5902:5901"  # VNC access  
      - "6654:6654"  # Emulator console
      - "6655:5555"  # ADB device port (mapped from internal 5555)
      - "6037:5037"  # ADB server port (mapped from internal 5037)
    # command: ["/usr/local/bin/start-emulator.sh"]
    command: ["sleep", "infinity"]  # Debug mode - commented out
  api:
    build:
      context: ./docker/api
    image: emulator-api
    ports:
      - "5001:5001"
      - "6080-6180:6080-6180"
    depends_on:
      - emulator
      - emulator14
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
