services:
  emulator:
    # platform: linux/amd64
    build:
      context: ./docker/emulator
    image: qemu-emulator
    privileged: true
    environment:
      - ANDROID_EMULATOR_WAIT_TIME=120
    devices:
      - /dev/kvm:/dev/kvm  # Only if KVM is available on host
    volumes:
      - ./avd-data:/root/.android/avd  # Optional: persist AVD data
    ports:
      - "5554:5554"  # Emulator console
      - "5555:5555"  # ADB connection
      - "5037:5037"  # ADB server
      - "5556-5560:5556-5560"  # Additional ports for device connections
    # network_mode: host  # Removing host network mode to use specific ports
    command: ["sh", "-c", "adb start-server && /usr/local/bin/start-emulator.sh && sleep infinity"]
  api:
    build:
      context: ./docker/api
    image: emulator-api
    ports:
      - "5001:5001"
    depends_on:
      - emulator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
